### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/r-i2p#1]
<img width="664" alt="Screen Shot 2022-11-09 at 1 04 54 PM" src="https://user-images.githubusercontent.com/50714166/200925861-6e166864-30f2-4a3b-82c8-472484834311.png">
<img width="676" alt="Screen Shot 2022-11-09 at 1 05 29 PM" src="https://user-images.githubusercontent.com/50714166/200925864-2d7a9ca1-a3f2-4d69-b0c7-69369abfef03.png">
<img width="680" alt="Screen Shot 2022-11-09 at 1 07 18 PM" src="https://user-images.githubusercontent.com/50714166/200925867-27816b5f-6c99-4501-9525-95b08246d652.png">
<img width="1048" alt="Screen Shot 2022-11-09 at 1 10 29 PM" src="https://user-images.githubusercontent.com/50714166/200925871-716352d9-59b2-4c70-a576-83d379c3aad1.png">
<img width="683" alt="Screen Shot 2022-11-09 at 1 10 44 PM" src="https://user-images.githubusercontent.com/50714166/200925873-e876d7f0-bbad-4555-bccf-2c9ded1748e7.png">
<img width="703" alt="Screen Shot 2022-11-09 at 1 20 46 PM" src="https://user-images.githubusercontent.com/50714166/200925875-0cb5ad12-9694-462b-8343-ade45c8beaa9.png">
<img width="471" alt="Screen Shot 2022-11-09 at 1 22 08 PM" src="https://user-images.githubusercontent.com/50714166/200925877-8bc60d81-ab4a-47c5-b597-6690f03b2e77.png">
<img width="519" alt="Screen Shot 2022-11-09 at 1 22 15 PM" src="https://user-images.githubusercontent.com/50714166/200925878-17ce7f6d-fb5d-4791-92c1-e9202903f2f9.png">

**Comment by Shoalsteed** [comment]
https://rebuildingalexandria.wordpress.com/2012/02/21/secure-and-anonymous-file-sharing-using-torrents-on-the-i2p-network-library-nu-exiles-take-a-look/

This links to a very outdated document. It should be considered for removal.

**Comment by Shoalsteed** [comment]
https://www.youtube.com/user/i2ptutorials

We should link to idk's yt channel of I2P stuff - this is all 10 years old and has not been updated.

**Comment by Shoalsteed** [comment]
https://pastebin.com/xWzw10wW

This resource looks like it was last updated in 2013. If that is true, it should be updated or replaced.

**Comment by eyedeekay** [comment]
> https://www.youtube.com/user/i2ptutorials
> 
> We should link to idk's yt channel of I2P stuff - this is all 10 years old and has not been updated.

IMO my youtube channel is not a good fit to replace i2ptutorials, the closest thing I have to a replacement for any of that content is https://eyedeekay.github.io/I2P-Easy-Install-the-Movie/ and https://eyedeekay.github.io/I2P-Without-Installiing-Anything-A-post-facto-prequel/ but that is still only a fraction of the i2ptutorials content. My channel is all mixed up with Freenet, Tor, Lokinet, Hashmatter, IPFS, computer science classes about DHT's, it's hardly even focused on I2P anymore.

**Comment by eyedeekay** [comment]
> https://pastebin.com/xWzw10wW
> 
> This resource looks like it was last updated in 2013. If that is true, it should be updated or replaced.

Probably just replace with not_bob right?

**Comment by Shoalsteed** [comment]
I would rather remove very outdated links to tutorials.

**Comment by Shoalsteed** [comment]
> > https://pastebin.com/xWzw10wW
> > This resource looks like it was last updated in 2013. If that is true, it should be updated or replaced.
> 
> Probably just replace with not_bob right?

Yes, just remove it keep active service directory resources.

**Comment by Shoalsteed** [comment]
@marek22k Do we agree to remove the dead links and resources that are older than 3- 5  years?

**Comment by marek22k** [comment]
Yes, maybe there are also some services in I2P that replace the current ones.
We have two dead file sharing services, two outdated DNS services, an unstable search engine, a dead email program and a dead tracker. I would leave Chudo DNS for now, since the website was working fine and the source code is on GitHub.

legwork.i2p I would also leave in - however it is very unstable.

Filesharing (upload and send):
- http://sharefile.i2p/
- http://fileshare.linuxfarm.i2p/
- http://cake.i2p/
- http://tmpsend.i2p/

Pastebins:
- http://privatebin.i2p/
- http://paste.idk.i2p/

YouTube Proxy:
- http://tube.i2p/
- http://invidious.qwik.i2p/

Twitter Proxy:
- http://natter.i2p/
- http://nitter.skank.i2p/

Wikipedia Proxy:
- http://wikiless.i2p/

BitTorrent tracker:
- http://tracker2.postman.i2p/
(The most are without user interface)

Search engine:
- http://legwork.i2p/
- http://yacy.idk.i2p/
- http://i2psearch.i2p/

News:
- http://planet.i2p/
- http://theguardian.i2p/

I2P related:
- http://i2p-projekt.i2p/
- http://wiki.i2p-projekt.i2p/
- http://i2pmetrics.i2p/

Tutorials:
- http://w3schools.i2p/
- http://privacy-handbuch.i2p/

DNS / Link collection:
- http://isitup.i2p/
- http://notbob.i2p/
- http://scanner.linuxfarm.i2p/
- http://stats.i2p/
- http://dns.chudo.i2p/

**Comment by eyedeekay** [comment]
Consider my yacy dead. I'm not maintaining it anymore, it's more trouble and stress than it's worth and Yacy keeps killing my computers.
